"""add email verification and otp fields

Revision ID: 599dd3870f13
Revises: 08a8638ede9a
Create Date: 2026-08-08 17:18:23.651638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '599dd3870f13'
down_revision: Union[str, Sequence[str], None] = '08a8638ede9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('email_otp_expiry', sa.DateTime(), nullable=True))
    op.alter_column('users', 'reset_otp_expiry',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(None, 'wallet_transactions', ['id'])
    op.create_unique_constraint(None, 'wallets', ['id'])
    op.create_unique_constraint(None, 'withdrawal_requests', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawal_requests', type_='unique')
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_constraint(None, 'wallet_transactions', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'reset_otp_expiry',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('users', 'email_otp_expiry')
    op.drop_column('users', 'email_otp')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
