from pgvector.sqlalchemy import Vector
"""add embeddings

Revision ID: 9d86f5e6e857
Revises: 599dd3870f13
Create Date: 2026-08-12 14:09:11.490440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d86f5e6e857'
down_revision: Union[str, Sequence[str], None] = '599dd3870f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('embeddings', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'embeddings')
    # ### end Alembic commands ###
