"""add product interactions table

Revision ID: eb728841a49f
Revises: 9d86f5e6e857
Create Date: 2026-08-14 11:47:24.331487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb728841a49f'
down_revision: Union[str, Sequence[str], None] = '9d86f5e6e857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.Enum('VIEW', 'CART', 'PURCHASE', 'WISHLIST', name='interactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_interactions_created_at'), 'product_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_interactions_interaction_type'), 'product_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_product_interactions_product_id'), 'product_interactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_interactions_user_id'), 'product_interactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_interactions_user_id'), table_name='product_interactions')
    op.drop_index(op.f('ix_product_interactions_product_id'), table_name='product_interactions')
    op.drop_index(op.f('ix_product_interactions_interaction_type'), table_name='product_interactions')
    op.drop_index(op.f('ix_product_interactions_created_at'), table_name='product_interactions')
    op.drop_table('product_interactions')
    # ### end Alembic commands ###
